<template>
  <div class="admin-dashboard">
    <div class="center-part-view-subheading mb1 no-border">
      <div class="fx fx-space-between fx-center">
        <h4 class="semi-bold">Shared URL</h4>
      </div>
    </div>
    <div
      class="simple-table nowrap-none table-responsive dashboard-admin-table"
    >
      <div class="tbody">
        <table>
          <thead>
            <tr>
              <th class="name">
                <span>Shared URL</span>
                <SortIcon />
              </th>
              <th class="project sorting">
                <span>Generated Date</span>
                <SortIcon />
              </th>
              <th class="work-type sorting">
                <span>Generated By</span>
                <SortIcon />
              </th>
              <th class="description sorting">
                <span>Generated Source</span>
                <SortIcon />
              </th>
              <th class="hours-type text-center">
                <span>Actions</span>
                <SortIcon />
              </th>
            </tr>
          </thead>
          <transition-group name="slide-up" tag="tbody">
            <SharedURLItem
              v-for="sharedURL in sharedURLs"
              :key="sharedURL.id"
              v-bind="{ sharedURL }"
            />
          </transition-group>
        </table>
      </div>
    </div>
  </div>
</template>

<script>
export default {
  layout: 'app-min-no-search',
  data() {
    return {
      sharedURLs: [],
    }
  },
}
</script>

<style></style>
