<template>
  <div class="body-content">
    <div class="body-content-auto w-100">
      <div class="common-box-header">
        <h2 class="title">Shared urls</h2>
      </div>
      <div class="common-box bg-gray">
        <div v-if="urls.length" class="table-list-view shared-url-table h-100">
          <ul class="thead">
            <li>
              <div class="share-url sorting flex50">
                <span>Shared URL</span>
              </div>
              <div
                :class="[
                  'generated-date sorting flex15 m-sm-hide sortarrow',
                  sortingClass('updated_at'),
                ]"
              >
                <span @click="sort('updated_at')">Generated Date</span>
              </div>
              <div
                :class="[
                  'generated-by sorting flex15 m-sm-hide sortarrow',
                  sortingClass('user_name'),
                ]"
              >
                <span @click="sort('user_name')">Generated By </span>
              </div>
              <div
                :class="[
                  'generated-source sorting flex15 m-sm-hide sortarrow',
                  sortingClass('generated_source'),
                ]"
              >
                <span @click="sort('generated_source')">Generated Source</span>
              </div>
              <div class="share-actions sorting flex5 text-center">
                <span>Action</span>
              </div>
            </li>
          </ul>
          <div class="customscrollbar">
            <transition-group name="slide-up" tag="ul" class="tbody">
              <SharedURLItem
                v-for="(url, i) in urls"
                :key="url.id"
                v-bind="{ url }"
                :style="`transition-delay: ${i * 25}ms`"
                @deleted="urls = urls.filter(({ id }) => id !== $event)"
              />
            </transition-group>
          </div>
        </div>
        <div v-else key="no-data" class="no-data-found">
          <div class="inner w-100">
            <img src="~/assets/img/no-data-image.svg" alt="" />
            <p>No Data Found</p>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
import SharedURLItem from '~/components/dam/SharedURLItem'

export default {
  components: { SharedURLItem },
  middleware: ['check-auth', 'check-url'],
  layout: 'app-min-no-search',
  asyncData({ $axios, $getWorkspaceId, error, $sortBy }) {
    return $axios
      .$get(`digital/list-share-assets-url?workspace_id=${$getWorkspaceId()}`)
      .then(({ data }) => ({
        urls: data
          .map(({ user, ...rest }) => ({
            ...rest,
            userName: user?.name || '-',
            user,
          }))
          .sort($sortBy('updated_at', true)),
      }))
      .catch((e) => error(e))
  },
  data() {
    return {
      deleting: false,
      sorting: {
        value: 'updated_at',
        desc: true,
      },
      sortDesc: false,
    }
  },
  methods: {
    sort(value) {
      let desc = false

      if (this.sorting.value !== value) desc = false
      else desc = !this.sorting.desc

      this.urls = [...this.urls].sort(this.$sortBy(value, desc))

      this.$nextTick(() => {
        this.sorting.value = value
        this.sorting.desc = desc
      })
    },
    sortingClass(value) {
      return {
        active: this.sorting.value === value && this.sorting.desc === true,
      }
    },
  },
}
</script>
