<template>
  <div class="admin-dashboard">
    <div class="center-part-view-subheading mb1 no-border">
      <div class="fx fx-space-between fx-center">
        <h4 class="semi-bold">Shared URL</h4>
      </div>
    </div>
    <div
      class="simple-table nowrap-none table-responsive dashboard-admin-table"
    >
      <div class="tbody">
        <table v-if="urls.length">
          <thead>
            <tr>
              <th class="name">
                <span>
                  Shared URL
                  <SortIcon />
                </span>
              </th>
              <th class="project sorting">
                <span>Generated Date</span>
                <SortIcon />
              </th>
              <th class="work-type sorting">
                <span>
                  Generated By
                  <SortIcon />
                </span>
              </th>
              <th class="description sorting">
                <span>
                  Generated Source
                  <SortIcon />
                </span>
              </th>
              <th class="hours-type text-center">
                <span>
                  Actions

                  <SortIcon />
                </span>
              </th>
            </tr>
          </thead>
          <transition-group name="slide-up" tag="tbody">
            <SharedURLItem
              v-for="(url, i) in urls"
              :key="url.id"
              v-bind="{ url }"
              :style="`transition-delay: ${i * 25}ms`"
              :deleting.sync="deleting"
              @deleted="urls = urls.filter(({ id }) => id !== $event)"
            />
          </transition-group>
        </table>
        <div v-else key="no-data" class="no-data-found">
          <img
            src="~/assets/img/no-data-image.svg"
            alt="No Data Found"
            class="img-responsive"
          />
          <h4>No Data Found</h4>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
import SharedURLItem from '~/components/dam/SharedURLItem'

export default {
  components: { SharedURLItem },
  layout: 'app-min-no-search',
  asyncData({ $axios, $getWorkspaceId, error }) {
    return $axios
      .$get(`digital/list-share-assets-url?workspace_id=${$getWorkspaceId()}`)
      .then(({ data }) => ({
        urls: data.map(({ user, ...rest }) => ({
          ...rest,
          userName: user?.name || '-',
          user,
        })),
      }))
      .catch((e) => error(e))
  },
  data() {
    return {
      deleting: false,
    }
  },
}
</script>
